version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.configs/postgres/.env
  solder:
    build: ./solder
    image: leonime/solder
    container_name: solder
    restart: on-failure
    env_file:
      - ./.configs/solder/.env
    volumes:
      - /data/docker/solder/database:/var/lib/postgresql/data
      - /data/docker/solder/repo:/var/www/repo.solder
      - /data/docker/solder/storage:/var/www/technicsolder/app/storage
    environment:
      - SOLDER_HOST=solder.example.com
      - REPO_HOST=repo.example.com
      - REPO_USER=username
      - REPO_PASSWORD=password
    ports:
      - 80:80
      - 8080:8080

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/.data/postgres/data
      o: bind